### ISSUE TITLE
Failed to build droidefense

### ISSUE THREAD

**Issue by Anemone95** [droidefense/engine#43]
I followed the construction in 

> https://github.com/droidefense/engine/wiki/Compilation

, but I got some mistakes:

```bash
root@kali:~/Desktop/CZY/MobileSec/MalwareDetection/tools/droidefense# ./build.sh
[ LOG ]  Installing prerequisites...
[ SUCCESS ] maven already installed
[ LOG ]  Cleaning current workdir...
[ LOG ]  Building droidefense from current version
[ LOG ] mvn clean package
...
INFO] Building jar: /mnt/hgfs/all_my_work/CZY/MobileSec/MalwareDetection/tools/droidefense/mods/simplemagic/target/simplemagic-javadoc.jar
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Droidefense - core 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.droidefense:axml:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Droidefense - logger ............................... SUCCESS [  4.644 s]
[INFO] Droidefense - axml parser (diff.rednaga) ........... SUCCESS [  7.295 s]
[INFO] Droidefense - datamanager .......................... SUCCESS [  2.500 s]
[INFO] Droidefense - entropy .............................. SUCCESS [  4.521 s]
[INFO] Droidefense - reporter ............................. SUCCESS [  5.582 s]
[INFO] Droidefense - rule engine .......................... SUCCESS [  2.464 s]
[INFO] Droidefense - ssdeep ............................... SUCCESS [  0.137 s]
[INFO] Droidefense - sdk .................................. SUCCESS [  5.445 s]
[INFO] Droidefense - androidManifest.xml parser ........... SUCCESS [  1.928 s]
[INFO] Droidefense - vfs .................................. SUCCESS [  1.233 s]
[INFO] Droidefense - ml ................................... SUCCESS [  0.687 s]
[INFO] Droidefense - portex ............................... SUCCESS [  1.495 s]
[INFO] Droidefense - pscout ............................... SUCCESS [  0.269 s]
[INFO] Droidefense - inmemory-apktool ..................... SUCCESS [03:05 min]
[INFO] Simple Magic ....................................... SUCCESS [02:57 min]
[INFO] Droidefense - core ................................. FAILURE [  0.040 s]
[INFO] Droidefense - plugins .............................. SKIPPED
[INFO] Droidefense - cli .................................. SKIPPED
[INFO] Droidefense - engine ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:14 min (Wall Clock)
[INFO] Finished at: 2018-02-03T21:38:16+08:00
[INFO] Final Memory: 39M/585M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project com.droidefense:core:jar:1.0-SNAPSHOT: Could not find artifact com.droidefense:axml:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core

```
My environment is like this:
```bash
root@kali:~/Desktop/CZY/MobileSec/MalwareDetection/tools/droidefense# mvn -v
Apache Maven 3.5.0
Maven home: /usr/share/maven
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.6.0-kali1-amd64", arch: "amd64", family: "unix"
```

**Comment by zerjioang** [comment]
Hi,

I have tested right now against my local environment with next maven config:

```
Apache Maven 3.5.0
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-32-generic", arch: "amd64", family: "unix"
```

having a successful compilation.As you can see, it is working for Travis CI too ( https://travis-ci.org/droidefense/engine ) so im wondering whether you have downloaded the latest version from develop branch or not.

Can you check that?

**Comment by Anemone95** [comment]
I think this problem is not caused by branch. As I checkout the newest version:
```bash
anemone@anemone-VirtualBox:/media/anemone/droidefense/engine$ git branch -a
* develop
  remotes/origin/HEAD -> origin/develop
  remotes/origin/develop
  remotes/origin/master
anemone@anemone-VirtualBox:/media/anemone/droidefense/engine$ git pull
Already up-to-date.
anemone@anemone-VirtualBox:/media/anemone/droidefense/engine$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
```
When I used `mvn package -e`, I got more information about the error:
```
**[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project com.droidefense:core:jar:1.0-SNAPSHOT: Could not find artifact com.droidefense:axml:jar:1.0-SNAPSHOT -> [Help 1]**
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project core: Could not resolve dependencies for project com.droidefense:core:jar:1.0-SNAPSHOT: Could not find artifact com.droidefense:axml:jar:1.0-SNAPSHOT
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at....
```
`core`  depends on `axml` as the `mods/core/pom.xml` (line 30-34) shows:
```xml
        <dependency>
            <groupId>com.droidefense</groupId>
            <artifactId>axml</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
```
But in root directory's `pom.xml`, I can not find any way to compile or get  `com.droidefense:axml`. At the same time I search the entire git project for axml module, but nothing. So I wonder if you ignore this folder in git or used a private maven repository.

**Comment by zerjioang** [comment]
yeah, good point @Anemone0 , I realize it was still there and it should have been removed (since axml module was replaced by another one, and name changed). I just updated the code, and sync repos. Can you pull it again? And let me know your results.

**Comment by Anemone95** [comment]
It works. Thank you! : p
